		<ul class="clearfix">
			<li class="txt"><a href="https://twitter.com/melancholic1331" target="_blank"><i class="fa fa-external-link"></i>お知らせ</a></li>
			<li class="txt"><a href="https://youtu.be/aLOipzXXyNI" target="_blank"><i class="fa fa-external-link"></i>予告編</a></li>
			<li class="txt"><a href="/melancholic/theater.php"><i class="fa fa-angle-right"></i>劇場情報</a></li>
			
			<li class="txt"><a href="/melancholic/#intro"><i class="fa fa-angle-right"></i>この映画について</a></li>
			<li class="txt"><a href="/melancholic/#comments"><i class="fa fa-angle-right"></i>コメント</a></li>
			<!--<li class="txt"><a href="/melancholic/#ticket"><i class="fa fa-angle-right"></i>劇場鑑賞券</a></li>-->
			
			<li class="icon twitter"><a href="https://twitter.com/melancholic1331" target="_blank"><i class="fa fa-twitter-square"></i><span class="sp">twitter</span></a></li>
			<li class="icon instagram"><a href="http://instagram.com/melancholic.jp/" target="_blank"><i class="fa fa-instagram"></i><span class="sp">instagram</span></a></li>
		</ul>

		<!--ul class="mini">
			<li><a href="" target="_blank"><i class="fa fa-ticket"></i></a></li>
		</ul-->