<a name="001" id="001" class="target"></a>
					<!-- ken-box_str -->
					<section class="ken-box clearfix">
						
						<div class="ken"><h2>関東</h2></div>
						<!-- theater-box_str -->
						<div class="theaters">
					
							
							<!-- box_str -->
							<a name="2824" id="2824"></a>
							<section class="theater-box clearfix">
								<div class="theater-name">
									<h4>東京</h4>
									<h3>アップリンク渋谷</h3>
								</div>
								<div class="txt">
									<p><strong>2019年8月3日(土)公開</strong></p>

                                <p>東京都渋谷区宇田川町37−18 トツネビル<br />
                                03-6825-5503<br />
                                <a href="https://shibuya.uplink.co.jp/movie/2019/54360">https://shibuya.uplink.co.jp/movie/2019/54360</a></p>
								</div>
							</section>
							<!-- box_end -->
							
							<!-- box_str -->
							<a name="2824" id="2824"></a>
							<section class="theater-box clearfix">
								<div class="theater-name">
									<h4>東京</h4>
									<h3>アップリンク吉祥寺</h3>
								</div>
								<div class="txt">
									<p><strong>2019年8月3日(土)公開</strong></p>

                                <p>東京都武蔵野市吉祥寺本町1丁目5−1 パルコ地下2階<br />
                                0422-66-5042<br />
                                <a href="https://joji.uplink.co.jp/movie/2019/2724">https://joji.uplink.co.jp/movie/2019/2724</a></p>
								</div>
							</section>
							<!-- box_end -->
							
							<!-- box_str -->
							<a name="2824" id="2824"></a>
							<section class="theater-box clearfix">
								<div class="theater-name">
									<h4>東京</h4>
									<h3>イオンシネマ むさし村山</h3>
								</div>
								<div class="txt">
									<p><strong>2019年8月3日(土)公開</strong></p>

                                <p>東京都武蔵村山市榎1丁目1−3 イオンモールむさし村山3Ｆ<br />
                                042-567-8717<br />
                                <a href="https://www.aeoncinema.com/cinema/musashino/">https://www.aeoncinema.com/cinema/musashino/</a></p>
								</div>
							</section>
							<!-- box_end -->
							
							<!-- box_str -->
							<a name="2824" id="2824"></a>
							<section class="theater-box clearfix">
								<div class="theater-name">
									<h4>神奈川</h4>
									<h3>イオンシネマ 港北ニュータウン</h3>
								</div>
								<div class="txt">
									<p><strong>2019年8月3日(土)公開</strong></p>

                                <p>神奈川県横浜市都筑区中川中央1-25-1 ノースポート・モール内<br />
                                045-914-7677<br />
                                <a href="https://cinema.aeoncinema.com/wm/kohoku/">https://cinema.aeoncinema.com/wm/kohoku/</a></p>
								</div>
							</section>
							<!-- box_end -->
							
							<!-- box_str -->
							<a name="2824" id="2824"></a>
							<section class="theater-box clearfix">
								<div class="theater-name">
									<h4>神奈川</h4>
									<h3>シネマ・ジャック＆ベティ</h3>
								</div>
								<div class="txt">
									<p><strong>近日公開</strong></p>

                                <p>神横浜市中区若葉町3-51<br />
                                045-243-9800<br />
                                <a href="http://www.jackandbetty.net/">http://www.jackandbetty.net/</a></p>
								</div>
							</section>
							<!-- box_end -->
							
							<!-- box_str -->
							<a name="2824" id="2824"></a>
							<section class="theater-box clearfix">
								<div class="theater-name">
									<h4>埼玉</h4>
									<h3>川越スカラ座</h3>
								</div>
								<div class="txt">
									<p><strong>近日公開</strong></p>

                                <p>埼玉県川越市元町1-1-1<br />
                                049-223-0733<br />
                                <a href="http://k-scalaza.com/">http://k-scalaza.com/</a></p>
								</div>
							</section>
							<!-- box_end -->
							
							<!-- box_str -->
							<a name="2824" id="2824"></a>
							<section class="theater-box clearfix">
								<div class="theater-name">
									<h4>群馬・高崎</h4>
									<h3>シネマテークたかさき</h3>
								</div>
								<div class="txt">
									<p><strong>2019年9月28日(土)～10月4日(金)</strong></p>

                                <p>群馬県高崎市あら町202番地<br />
                                027-325-1744<br />
                                <a href="hhttp://takasaki-cc.jp/">http://takasaki-cc.jp/</a></p>
								</div>
							</section>
							<!-- box_end -->
							
														
							<!-- box_str -->
							<a name="2824" id="2824"></a>
							<section class="theater-box clearfix last">
								<div class="theater-name">
									<h4>茨城</h4>
									<h3>あまや座</h3>
								</div>
								<div class="txt">
									<p><strong>近日公開</strong></p>

                                <p>茨城県那珂市瓜連1243（スーパーあまや 駐車場内）<br />
                                029-212-7531<br />
                                <a href="http://amaya-za.com/">http://amaya-za.com/</a></p>
								</div>
							</section>
							<!-- box_end -->
							
							
						</div>
						<!-- theater-box_end -->
					</section>
					<!-- ken-box_end -->
					
					<a name="002" id="002" class="target"></a>
					<!-- ken-box_str -->
					<section class="ken-box clearfix">
						
						<div class="ken"><h2>北海道・東北</h2></div>
						<!-- theater-box_str -->
						 <div class="theaters">
					
							<!-- box_str -->
							<a name="2824" id="2824"></a>
							<section class="theater-box clearfix last">
								<div class="theater-name">
									<h4>宮城</h4>
									<h3>チネ・ラヴィータ</h3>
								</div>
								<div class="txt">
									<p><strong>2019年9月13日(金)～9月26日(木)</strong></p>

                                <p>宮城県仙台市宮城野区榴岡2-1-25<br />
                                022-299-5555<br />
                                <a href="http://forum-movie.net/sendai/">http://forum-movie.net/sendai/</a></p>
								</div>
							</section>
							<!-- box_end -->

</div>
						<!-- theater-box_end -->
					</section>
					<!-- ken-box_end -->
					
					<!-- <a name="003" id="003" class="target"></a> -->
					<!-- ken-box_str -->
					<!-- <section class="ken-box clearfix"> -->
						
						<!-- <div class="ken"><h2>甲信越・北陸</h2></div> -->
						<!-- theater-box_str -->
						<!-- <div class="theaters"> -->
					

						<!-- </div> -->
						<!-- theater-box_end -->
					<!-- </section> -->
					<!-- ken-box_end -->
					
					<a name="004" id="004" class="target"></a>
					<!-- ken-box_str -->
					<section class="ken-box clearfix">
						
						<div class="ken"><h2>中部</h2></div>
						<!-- theater-box_str -->
						<div class="theaters">
					
							
							<!-- box_str -->
							<a name="2852" id="2852"></a>
							<section class="theater-box clearfix">
								<div class="theater-name">
									<h4>愛知</h4>
									<h3>シネマスコーレ</h3>
								</div>
								<div class="txt">
									<p><strong>2019年8月24日(土)～9月6日(金)</strong></p>

                              <p>愛知県名古屋市中村区椿町８−１２ ふらっと1F<br />
                              052-452-6036<br />
                              <a href="http://www.cinemaskhole.co.jp/cinema/html/">http://www.cinemaskhole.co.jp/cinema/html/</a></p>
								</div>
							</section>
							<!-- box_end -->
							
							<!-- box_str -->
							<a name="2852" id="2852"></a>
							<section class="theater-box clearfix">
								<div class="theater-name">
									<h4>三重・伊勢</h4>
									<h3>伊勢新富座</h3>
								</div>
								<div class="txt">
									<p><strong>2019年9月21日(土)～10月4日(金)</strong></p>

                              <p>三重県伊勢市曽祢2-8-27<br />
                              0596-28-2875<br />
                              <a href="http://www.h5.dion.ne.jp/~shintomi/">http://www.h5.dion.ne.jp/~shintomi/</a></p>
								</div>
							</section>
							<!-- box_end -->
							
								<!-- box_str -->
							<a name="2852" id="2852"></a>
							<section class="theater-box clearfix last">
								<div class="theater-name">
									<h4>長野</h4>
									<h3>松本CINEMAセレクト</h3>
								</div>
								<div class="txt">
									<p><strong>2019年9月15日(日)1日1回のみの限定上映</strong></p>

                              <p>0263-98-4928<br />
                              <a href="http://www.cinema-select.com/">http://www.cinema-select.com/</a></p>
								</div>
							</section>
							<!-- box_end -->
							
							

							
						</div>
						<!-- theater-box_end -->
					</section>
					<!-- ken-box_end -->
					
					<a name="005" id="005" class="target"></a>
					<!-- ken-box_str -->
					<section class="ken-box clearfix">
						
						<div class="ken"><h2>近畿</h2></div>
						<!-- theater-box_str -->
						<div class="theaters">
					
							
							<!-- box_str -->
							<a name="2826" id="2826"></a>
							<section class="theater-box clearfix">
								<div class="theater-name">
									<h4>大阪</h4>
									<h3>第七藝術劇場</h3>
								</div>
								<div class="txt">
									<p><strong>2019年9月14日(土)公開</strong></p>

                                  <p>大阪府大阪市淀川区十三本町1丁目7−27 サンポードシティ<br />
                                  06-6302-2073<br />
                                  <a href="http://www.nanagei.com/">http://www.nanagei.com/</a></p>
								</div>
							</section>
							<!-- box_end -->							

							<!-- box_str -->
							<a name="2826" id="2826"></a>
							<section class="theater-box clearfix">
								<div class="theater-name">
									<h4>大阪</h4>
									<h3>シネ・ヌーヴォ</h3>
								</div>
								<div class="txt">
									<p><strong>2019年9月14日(土)公開</strong></p>

                                  <p>大阪府大阪市西区九条1丁目20−24<br />
                                  06-6582-1416<br />
                                  <a href="http://www.cinenouveau.com/">http://www.cinenouveau.com/</a></p>
								</div>
							</section>
							<!-- box_end -->							
							
							<!-- box_str -->
							<a name="2826" id="2826"></a>
							<section class="theater-box clearfix">
								<div class="theater-name">
									<h4>兵庫・神戸</h4>
									<h3>元町映画館</h3>
								</div>
								<div class="txt">
									<p><strong>近日公開</strong></p>

                                  <p>兵庫県神戸市中央区元町通4丁目1-12<br />
                                  078-366-2636<br />
                                  <a href="http://www.motoei.com/">http://www.motoei.com/</a></p>
								</div>
							</section>
							<!-- box_end -->
							
							
							<!-- box_str -->
							<a name="2826" id="2826"></a>
							<section class="theater-box clearfix">
								<div class="theater-name">
									<h4>京都</h4>
									<h3>イオンシネマ京都桂川</h3>
								</div>
								<div class="txt">
									<p><strong>2019年8月16日(金)公開</strong></p>

                                  <p>京都府京都市南区久世高田町376−1 イオンモール京都桂川<br />
                                  075-925-0075<br />
                                  <a href="https://cinema.aeoncinema.com/wm/katsuragawa/">https://cinema.aeoncinema.com/wm/katsuragawa/</a></p>
								</div>
							</section>
							<!-- box_end -->
							
							
							<!-- box_str -->
							<a name="2826" id="2826"></a>
							<section class="theater-box clearfix last">
								<div class="theater-name">
									<h4>京都</h4>
									<h3>京都みなみ会館</h3>
								</div>
								<div class="txt">
									<p><strong>近日公開</strong></p>

                                  <p>2019年夏、移転再オープン<br />
                                  <a href="http://kyoto-minamikaikan.jp/">http://kyoto-minamikaikan.jp/</a></p>
								</div>
							</section>
							<!-- box_end -->
							
						</div>
						<!-- theater-box_end -->
					</section>
					<!-- ken-box_end -->
					
					<a name="006" id="006" class="target"></a>
					<!-- ken-box_str -->
					<section class="ken-box clearfix">
						
						<div class="ken"><h2>中国・四国</h2></div>
						<!-- theater-box_str -->
						<div class="theaters">
					
							<!-- box_str -->
							<a name="2826" id="2826"></a>
							<section class="theater-box clearfix">
								<div class="theater-name">
									<h4>広島</h4>
									<h3>横川シネマ</h3>
								</div>
								<div class="txt">
									<p><strong>近日公開</strong></p>

                                  <p>広島県広島市西区横川町3-1-12<br />
                                  082-231-1001<br />
                                  <a href="http://yokogawa-cine.jugem.jp/">http://yokogawa-cine.jugem.jp/</a></p>
								</div>
							</section>
							<!-- box_end -->
							
											
							<!-- box_str -->
							<a name="2826" id="2826"></a>
							<section class="theater-box clearfix last">
								<div class="theater-name">
									<h4>広島・福山</h4>
									<h3>福山駅前シネマモード</h3>
								</div>
								<div class="txt">
									<p><strong>2019年9月6日(金)～9月19日(木)</strong></p>

                                  <p>広島県福山市伏見町4−33<br />
                                  084-932-3381<br />
                                  <a href="http://www.furec.jp/cinema-mode/schedule/">http://www.furec.jp/cinema-mode/schedule/</a></p>
								</div>
							</section>
							<!-- box_end -->
							
						</div>
						<!-- theater-box_end -->
					</section>
					<!-- ken-box_end -->
					
				<a name="007" id="007" class="target"></a>
					<!-- ken-box_str -->
					<section class="ken-box clearfix">
						
						<div class="ken"><h2>九州・沖縄</h2></div>
						<!-- theater-box_str -->
						<div class="theaters">
						
						
							<!-- box_str -->
							<a name="2826" id="2826"></a>
							<section class="theater-box clearfix">
								<div class="theater-name">
									<h4>福岡</h4>
									<h3>ユナイテッド・シネマ キャナルシティ13</h3>
								</div>
								<div class="txt">
									<p><strong>2019年10月18日(金)～10月31日(木)</strong></p>

                                  <p>福岡県福岡市博多区住吉1丁目2-22　キャナルシティ博多内<br />
                                  092-272-1515<br />
                                  <a href="http://www.unitedcinemas.jp/canalcity/index.html">http://www.unitedcinemas.jp/canalcity/index.html</a></p>
								</div>
							</section>
							<!-- box_end -->
						
					<!-- box_str -->
							<a name="2826" id="2826"></a>
							<section class="theater-box clearfix last">
								<div class="theater-name">
									<h4>大分</h4>
									<h3>シネマ５</h3>
								</div>
								<div class="txt">
									<p><strong>2019年9月14日(土)～9月19日(木)</strong></p>

                                  <p>大分県大分市府内町2-4-8<br />
                                  097-536-4512<br />
                                  <a href="http://www.cinema5.gr.jp/">http://www.cinema5.gr.jp/</a></p>
								</div>
							</section>
							<!-- box_end -->
							

							
						</div>
						<!-- theater-box_end -->
					</section>
					<!-- ken-box_end -->
					